# Generated by Django 4.2.19 on 2026-03-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_language_options_sitesettings_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mooto_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mooto_rw',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
