# Generated by Django 4.2.19 on 2026-04-09 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_summary_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('order', models.IntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_fields', to='news.language')),
            ],
            options={
                'verbose_name': 'Research Field',
                'verbose_name_plural': 'Research Fields',
                'ordering': ['order'],
                'unique_together': {('language', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Full title of the paper', max_length=400)),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
                ('sub_title', models.CharField(blank=True, help_text='Subtitle (optional)', max_length=400)),
                ('authors', models.TextField(help_text='Comma-separated list of author names. E.g. "Dr. Jane Uwimana, Prof. John Habimana"')),
                ('institution', models.CharField(blank=True, help_text='Publishing institution / university', max_length=300)),
                ('contact_email', models.EmailField(blank=True, help_text='Corresponding author email (optional)', max_length=254)),
                ('journal', models.CharField(blank=True, help_text='Journal or conference name', max_length=300)),
                ('volume', models.CharField(blank=True, help_text='Volume number', max_length=50)),
                ('issue', models.CharField(blank=True, help_text='Issue number', max_length=50)),
                ('pages', models.CharField(blank=True, help_text='Page range, e.g. "12–34"', max_length=50)),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier, e.g. 10.1234/abc', max_length=200, verbose_name='DOI')),
                ('issn', models.CharField(blank=True, help_text='International Standard Serial Number', max_length=20, verbose_name='ISSN')),
                ('isbn', models.CharField(blank=True, help_text='For books / book chapters', max_length=20, verbose_name='ISBN')),
                ('published_date', models.DateField(blank=True, help_text='Official publication date of the paper', null=True)),
                ('abstract', models.TextField(help_text='Full abstract / executive summary (displayed on site)')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for search & SEO', max_length=500)),
                ('methodology', models.TextField(blank=True, help_text='Brief methodology description (optional)')),
                ('findings', models.TextField(blank=True, help_text='Key findings / conclusions (optional)')),
                ('pdf_file', models.FileField(blank=True, help_text='Upload the paper PDF', null=True, upload_to='papers/pdfs/%Y/')),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image or thumbnail', null=True, upload_to='papers/covers/%Y/')),
                ('external_url', models.URLField(blank=True, help_text='External DOI / journal URL (used if no PDF is uploaded)')),
                ('supplementary', models.FileField(blank=True, help_text='Supplementary data file (optional)', null=True, upload_to='papers/supplementary/%Y/')),
                ('peer_reviewed', models.CharField(choices=[('yes', 'Peer Reviewed'), ('no', 'Not Peer Reviewed'), ('pending', 'Under Review')], default='no', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on Research Paper homepage block')),
                ('is_open_access', models.BooleanField(default=True, help_text='Mark paper as open access', verbose_name='Open Access')),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('downloads', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Date submitted to the site', null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_papers', to='news.language')),
                ('research_field', models.ForeignKey(blank=True, help_text='Primary academic discipline', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='news.researchfield')),
                ('sub_category', models.ForeignKey(blank=True, help_text='News topic tag (cross-links with news)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_papers', to='news.subcategory')),
            ],
            options={
                'verbose_name': 'Research Paper',
                'verbose_name_plural': 'Research Papers',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('affiliation', models.CharField(blank=True, help_text='Institution / affiliation (optional)', max_length=200)),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_comments', to='news.researchpaper')),
            ],
            options={
                'verbose_name': 'Paper Comment',
                'verbose_name_plural': 'Paper Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cited_by', models.CharField(help_text='Title of the citing paper', max_length=400)),
                ('cited_by_doi', models.CharField(blank=True, max_length=200, verbose_name='Citing paper DOI')),
                ('cited_by_url', models.URLField(blank=True, help_text='URL of the citing paper')),
                ('cited_by_authors', models.CharField(blank=True, max_length=300)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='news.researchpaper')),
            ],
            options={
                'verbose_name': 'Citation',
                'verbose_name_plural': 'Citations',
                'ordering': ['-year', '-created_at'],
            },
        ),
    ]
